services:
  - type: worker
    name: bot-argento
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PIONEX_API_KEY
        sync: false
      - key: PIONEX_SECRET_KEY
        sync: false
      - key: DRY_RUN
        value: "1"
      - key: SILVER_SYMBOL
        sync: false
      - key: SILVER_BUY_AMOUNT_USDT
        value: "5"
      - key: TOTAL_CAPITAL
        value: "67.0"
      - key: TRADE_MARGIN
        value: "5.0"
      - key: MIN_USDT_RESERVE
        value: "10.0"
      - key: ENABLE_SILVER_ACCUMULATION
        value: "1"
      - key: VOLATILE_TARGETS
        value: "BTC_USDT,ETH_USDT,SOL_USDT"
      - key: MICRO_TRADE_QUANTITY
        value: "0.01"
