services:
  - type: worker
    name: bot-argento
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PIONEX_API_KEY
        sync: false
      - key: PIONEX_SECRET_KEY
        sync: false
      - key: DRY_RUN
        value: "1"
      - key: SILVER_SYMBOL
        sync: false
      - key: SILVER_BUY_AMOUNT_USDT
        value: "5"
      - key: ENABLE_SILVER_ACCUMULATION
        value: "0"
      - key: MIN_USDT_RESERVE
        value: "10.0"
      - key: TARGET_USDT_AFTER_REBALANCE
        value: "10.0"
      - key: REBALANCE_COOLDOWN_SEC
        value: "300"
      - key: MIN_XAG_NOTIONAL_TO_SELL
        value: "2.0"
